# Generated by Django 2.2.3 on 2019-08-02 09:04

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDemandeAttestatation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_demande', models.CharField(choices=[('travail', 'Attestation Travail'), ('salaire', 'Attestation Salaire'), ('domiciliation', 'Domiciliation')], max_length=15, unique=True, verbose_name="Type de la demande d'attestation")),
            ],
            options={
                'verbose_name': "Type d'attestation",
                'verbose_name_plural': 'Type des attestations',
            },
        ),
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Envoyée')),
                ('etat_validation', models.BooleanField(default=False, verbose_name='Etat de Validation')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de Validation')),
                ('employe', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='Employe')),
                ('type', models.ForeignKey(on_delete=None, to='Gestion_Attestations.TypeDemandeAttestatation', verbose_name='Type de demande')),
            ],
            options={
                'verbose_name': 'Demande Attestation',
                'verbose_name_plural': 'Demandes des Attestations',
            },
        ),
    ]
