# Generated by Django 2.2.3 on 2019-08-02 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
        ('Gestion_Attestations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('matricule_paie', models.OneToOneField(db_column='matricule_paie', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('valeur_brute', models.IntegerField(verbose_name='Salaire Brute')),
            ],
            options={
                'verbose_name': 'Salaire',
                'verbose_name_plural': 'Salaires',
            },
        ),
    ]
