# Generated by Django 2.2.3 on 2019-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Attestations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedemandeattestataion',
            options={'verbose_name': "Type d'attestation", 'verbose_name_plural': 'Type des attestations'},
        ),
        migrations.AlterField(
            model_name='typedemandeattestataion',
            name='nom_type_demande',
            field=models.CharField(choices=[('travail', 'Attestation Travail'), ('salaire', 'Attestation Salaire'), ('domiciliation', 'Domiciliation')], max_length=15, unique=True, verbose_name="Type de la demande d'attestation"),
        ),
    ]
