# Generated by Django 2.2.3 on 2019-08-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Attestations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeDemandeAttestatation',
            new_name='TypeDemandeAttestation',
        ),
    ]
