# Generated by Django 2.2.3 on 2019-08-01 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=30, unique=True, verbose_name='Departement')),
                ('nbr_employes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricule_paie', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Matricule Paie')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prénom')),
                ('fonction', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fonction')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'FEMININ')], max_length=1, null=True, verbose_name='Sexe')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ville')),
                ('n_cin', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Numero Cin')),
                ('nationalite_paie', models.CharField(blank=True, max_length=3, null=True, verbose_name='Nationalité Paie')),
                ('situation_famille', models.CharField(blank=True, choices=[('C', 'Celibataire'), ('M', 'Marie')], max_length=1, null=True, verbose_name='Situation de famille')),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name='Date Entrée')),
                ('date_anciennete', models.DateField(blank=True, null=True, verbose_name='Date Anciennete')),
                ('n_cnss', models.IntegerField(blank=True, null=True, verbose_name='Numéro CNSS')),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de Sortie')),
                ('type_contrat', models.CharField(blank=True, max_length=6, null=True, verbose_name='Type de Contrat')),
                ('date_fin_contrat', models.DateField(blank=True, null=True, verbose_name='Date Fin Contrat')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Adresse Electronique')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentification.Departement', verbose_name='Département')),
                ('superieur_hierarchique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Supérieur Hierarchique')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='directeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
