# Generated by Django 2.2.3 on 2019-09-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_Activité')),
                ('nom_activite', models.CharField(max_length=20, verbose_name='Nom Activité')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_agence')),
                ('nom_agence', models.CharField(max_length=20, verbose_name='Nom Agence')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_cost_center')),
                ('nom_cost_center', models.CharField(max_length=20, verbose_name='Nom Cost Center')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_Département')),
                ('nom_departement', models.CharField(max_length=50, unique=True, verbose_name='Nom Département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_Service')),
                ('nom_service', models.CharField(max_length=50, verbose_name='Nom Service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricule_paie', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Matricule Paie')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nom Prénom')),
                ('fonction', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fonction')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'FEMININ')], max_length=1, null=True, verbose_name='Sexe')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ville')),
                ('n_cin', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Numéro de Cin')),
                ('nationalite_paie', models.CharField(blank=True, max_length=3, null=True, verbose_name='Nationalité Paie')),
                ('situation_famille', models.CharField(blank=True, choices=[('C', 'Célibataire'), ('M', 'Marié')], max_length=1, null=True, verbose_name='Situation de famille')),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name='Date Entrée')),
                ('date_anciennete', models.DateField(blank=True, null=True, verbose_name='Date Ancienneté')),
                ('n_cnss', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numéro CNSS')),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de Sortie')),
                ('type_contrat', models.CharField(blank=True, max_length=6, null=True, verbose_name='Type de Contrat')),
                ('date_fin_contrat', models.DateField(blank=True, null=True, verbose_name='Date Fin Contrat')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Adresse Electronique')),
                ('n_compte', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Numéro de Compte RIB')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('consultant_attestations', models.BooleanField(default=False)),
                ('consultant_conges', models.BooleanField(default=False)),
                ('consultant_recrutements', models.BooleanField(default=False)),
                ('consultant_fiches_objectifs', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentification.Activite', verbose_name='Activité')),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentification.Agence', verbose_name='Agence')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentification.CostCenter', verbose_name='Cost Center')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentification.Departement', verbose_name='Département')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentification.Service', verbose_name='Service')),
                ('superieur_hierarchique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Supérieur Hiérarchique')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='directeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
