# Generated by Django 2.2.3 on 2019-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Department_id'),
        ),
    ]
