# Generated by Django 2.2.3 on 2019-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='n_compte',
            field=models.CharField(default='test', max_length=25, unique=True, verbose_name='Numéro de Compte RIB'),
            preserve_default=False,
        ),
    ]
