# Generated by Django 2.2.3 on 2019-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='nb_enfant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='nb_enfant_deduction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
