# Generated by Django 2.2.3 on 2019-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_employe_n_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='n_cin',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Numero Cin'),
        ),
    ]
