# Generated by Django 2.2.3 on 2019-07-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentification.Departement', verbose_name='Département'),
        ),
    ]
