# Generated by Django 2.2.3 on 2019-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_auto_20190802_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='nbr_employes',
        ),
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id_Departement'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom_departement',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nom_Departement'),
        ),
    ]
