# Generated by Django 2.2.3 on 2019-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_auto_20190802_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=50, verbose_name='Nom Service'),
        ),
    ]
