# Generated by Django 2.2.3 on 2019-07-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_employe_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
    ]
