# Generated by Django 2.2.3 on 2019-08-01 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_auto_20190801_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_brute', models.IntegerField(verbose_name='Salaire Brute')),
                ('employe', models.OneToOneField(db_column='matricule_paie', on_delete=django.db.models.deletion.CASCADE, related_name='Salaire', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Salaire',
                'verbose_name_plural': 'Salaires',
            },
        ),
    ]
