# Generated by Django 2.2.3 on 2019-08-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_auto_20190802_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='directeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
