# Generated by Django 2.2.3 on 2019-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0004_auto_20190802_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Adresse Electronique'),
        ),
    ]
