# Generated by Django 2.2.3 on 2019-08-01 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0004_salaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaire',
            name='id',
        ),
        migrations.AlterField(
            model_name='salaire',
            name='employe',
            field=models.OneToOneField(db_column='matricule_paie', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Salaire', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Employé'),
        ),
    ]
