# Generated by Django 2.2.3 on 2019-08-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_auto_20190802_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Adresse Electronique'),
        ),
    ]
