# Generated by Django 2.2.3 on 2019-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_auto_20190801_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='employe',
            field=models.CharField(db_column='matricule_paie', max_length=10, primary_key=True, serialize=False, verbose_name='Employé'),
        ),
    ]
