# Generated by Django 2.2.3 on 2019-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_employe_solde_conge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='nom_departement',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom Département'),
        ),
    ]
