# Generated by Django 2.2.3 on 2019-08-01 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0006_auto_20190801_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaire',
            name='employe',
        ),
        migrations.AddField(
            model_name='salaire',
            name='matricule_paie',
            field=models.OneToOneField(db_column='matricule_paie', default='test', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Employé'),
            preserve_default=False,
        ),
    ]
