# Generated by Django 2.2.3 on 2019-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0006_auto_20190806_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='consultant_attestations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='consultant_conges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='consultant_recrutments',
            field=models.BooleanField(default=False),
        ),
    ]
