# Generated by Django 2.2.3 on 2019-08-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0007_auto_20190807_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='consultant_recrutments',
            new_name='consultant_recrutements',
        ),
    ]
