# Generated by Django 2.2.3 on 2019-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0008_auto_20190807_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='n_cnss',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numéro CNSS'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='n_compte',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Numéro de Compte RIB'),
        ),
    ]
