# Generated by Django 2.2.3 on 2019-08-27 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.IntegerField(verbose_name='Solde de Congé')),
                ('matricule_paie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Solde de Congé',
                'verbose_name_plural': 'Les soldes des congés',
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField(verbose_name='Date Départ en Congé')),
                ('date_retour', models.DateField(verbose_name='Date Retour du Congé')),
                ('jours_ouvrables', models.PositiveIntegerField(verbose_name='Jours Ouvrables')),
                ('interim', models.CharField(blank=True, max_length=60, null=True, verbose_name='Intérim assuré par')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone personnel')),
                ('etat', models.PositiveSmallIntegerField(choices=[(1, 'En attente de validation par le supérieur hiérachique'), (2, 'En attente de validation par la direction concernée'), (3, 'En attente de validation par la direction RH'), (4, 'Demande de Congé validée'), (0, 'Demande de Congé refusée')], default=1, verbose_name='Etat Demande')),
                ('date_envoi', models.DateField(default=django.utils.timezone.now, verbose_name='Date envoi de la demande du Congé')),
                ('date_sup', models.DateField(blank=True, null=True, verbose_name='Date validation Hiérarchie')),
                ('date_direction', models.DateField(blank=True, null=True, verbose_name='Date validation Direction Concernée')),
                ('date_direction_rh', models.DateField(blank=True, null=True, verbose_name='Date validation direction RH')),
                ('employe', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Demande Congé',
                'verbose_name_plural': 'Demandes des Congés',
            },
        ),
    ]
