# Generated by Django 2.2.3 on 2019-08-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Conge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeconge',
            options={'verbose_name': 'Demande Congé', 'verbose_name_plural': 'Demandes des Congés'},
        ),
    ]
