# Generated by Django 2.2.3 on 2019-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='no_reply',
            field=models.BooleanField(default=False, verbose_name='Pas de réponse nécessaire'),
        ),
    ]
