# Generated by Django 2.2.3 on 2019-08-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notification_no_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='no_reply',
            field=models.BooleanField(default=True, verbose_name='Pas de réponse nécessaire'),
        ),
    ]
