# Generated by Django 2.2.3 on 2019-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_auto_20190826_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
