# Generated by Django 2.2.3 on 2019-08-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_auto_20190806_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
